--- #YAML:1.0
name:                List-Compare
version:             0.37
abstract:            Compare elements of two or more lists
license:             ~
author:              
    - James E Keenan (jkeenan@cpan.org)
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::Simple:                  0.1
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
