--- #YAML:1.0
name:                List-Compare
version:             0.34
abstract:            Compare elements of two or more lists
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Test::Simple:                  0.1
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - James E Keenan (jkeenan@cpan.org)
